version: "3.8"

services:
  gha-runner:
    image: ghcr.io/myoung34/docker-github-actions-runner:latest
    container_name: gha-runner
    restart: unless-stopped

    # OPTIONAL: allow docker builds inside jobs by binding host docker socket
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    environment:
      RUNNER_SCOPE: "org"
      ORG_NAME: "${GITHUB_ORGA}"
      ACCESS_TOKEN: "${GITHUB_PAT}"         # store in Dokploy as an env secret
      RUNNER_NAME_PREFIX: "dokploy"         # will append a random suffix
      RUNNER_LABELS: "dokploy,linux,x64"    # use in 'runs-on' matrix
      EPHEMERAL: "true"                     # one job → auto-deregister
